In [72]:
import pandas as pd
import re

In [73]:
# logic.py
"""
Python port of your loan suggestion logic from logic.js.
Functions:
  - update_with_la(records, la)
  - update_with_da(records, da)
  - query_complex(scenarios, deposit_amount=None, repayment_duration=None,
                  deposit_duration=None, interest_rate=None, credit_score=None)
  - calculate_sort_order(loan)

Expect each record to be a dict with fields matching your JS schema.
Requires a JSON file 'parameters_weights.json' in the same directory.
"""
import json
from typing import List, Dict, Any, Optional

# Load parameter weights once
def _load_weights() -> Dict[str, Any]:
    with open('parameters_weights.json', 'r', encoding='utf-8') as f:
        return json.load(f)

_parameters_weights = _load_weights()

In [74]:
import json
from typing import List, Dict, Any, Optional

# Load parameter weights once
def _load_record() -> Dict[str, Any]:
    with open('MEC-LoanRecomn_Scenarios-V15.json', 'r', encoding='utf-8') as f:
        return json.load(f)

_records = _load_record()

In [75]:
_records

[{'id': 1,
  'nickname': 'بهان(بدون ضامن)',
  'package_name': 'فرابانک',
  'contract_type': 'مرابحه',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 1000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 60,
  'loan_coefficient': 1000,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': 'nan',
  'minimum_loan_amount': 100000000,
  'guarantee': 'خیر',
  'receiving_channel': 'غیر حضوری'},
 {'id': 2,
  'nickname': 'بهان(بدون ضامن)',
  'package_name': 'فرابانک',
  'contract_type': 'مرابحه',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 1000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 60,
  'loan_coefficient': 1000,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': 'nan',
  'minimum_loan_amount': 100000000,
  'guarantee': 'خیر',
  'receiving_channel': 'غیر حضوری'},
 {'id': 3,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 1,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 50,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 4,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 150,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 5,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 300,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 6,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 55,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 7,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 60,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 8,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 30,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 9,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 35,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 10,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 18,
  'repayment_duration': 12,
  'loan_coefficient': 80,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 11,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 18,
  'repayment_duration': 12,
  'loan_coefficient': 100,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 12,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 200,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 13,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 450,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 14,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 80,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 15,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 100,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 16,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 50,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 17,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 60,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 18,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 48,
  'loan_coefficient': 30,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 19,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 23,
  'repayment_duration': 48,
  'loan_coefficient': 35,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 20,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 14,
  'repayment_duration': 12,
  'loan_coefficient': 90,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 21,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 14,
  'repayment_duration': 12,
  'loan_coefficient': 110,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 22,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 12,
  'loan_coefficient': 170,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 23,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 12,
  'loan_coefficient': 200,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 24,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 14,
  'repayment_duration': 24,
  'loan_coefficient': 45,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 25,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 24,
  'loan_coefficient': 75,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 26,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 24,
  'loan_coefficient': 70,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 27,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 150,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 28,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 200,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 29,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 36,
  'loan_coefficient': 50,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 30,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 18,
  'repayment_duration': 36,
  'loan_coefficient': 45,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 31,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 110,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 32,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 125,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 33,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 48,
  'loan_coefficient': 75,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 34,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 6,
  'interest_rate': 23,
  'repayment_duration': 48,
  'loan_coefficient': 90,
  'credit_score': 'A',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 35,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 1,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 50,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 36,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 150,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 37,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 12,
  'loan_coefficient': 300,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 38,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 55,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 39,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 24,
  'loan_coefficient': 60,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 40,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 30,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 41,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',
  'granted_method': 'کارت اعتباری',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 2,
  'interest_rate': 23,
  'repayment_duration': 36,
  'loan_coefficient': 35,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 42,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه/جعاله',
  'granted_method': 'واریز به حساب',
  'loan_amount_limit': 3000000000,
  'deposit_duration': 3,
  'interest_rate': 18,
  'repayment_duration': 12,
  'loan_coefficient': 80,
  'credit_score': 'B',
  'minimum_deposit_amount': 'nan',
  'maximum_deposit_amount': '15000000000',
  'minimum_loan_amount': 100000000,
  'guarantee': 'بله',
  'receiving_channel': 'غیر حضوری/ حضوری'},
 {'id': 43,
  'nickname': 'شایان',
  'package_name': 'شایان یک',
  'contract_type': 'مرابحه',

In [76]:
def calculate_sort_order(loan: Dict[str, Any]) -> None:
    """
    Mutates loan by adding a 'sortOrder' key based on weighted criteria,
    faithfully mirroring the JS logic.
    """
    # Determine bucket
    loanAmountKey = 'out_of_range'
    la = loan.get('loan_amount', 0)
    if la <= 500_000_000:
        loanAmountKey = '1-50'
    elif la <= 1_000_000_000:
        loanAmountKey = '50-100'
    elif la <= 1_500_000_000:
        loanAmountKey = '100-150'
    elif la <= 2_000_000_000:
        loanAmountKey = '150-200'
    elif la <= 2_500_000_000:
        loanAmountKey = '200-250'
    elif la <= 3_000_000_000:
        loanAmountKey = '250-300'

    pw = _parameters_weights
    # Extract individual weights
    ir_key = str(loan.get('interest_rate', ''))
    rd_key = str(loan.get('repayment_duration', ''))
    dd_key = str(loan.get('deposit_duration', ''))
    # CS: first A-E or N
    cs_match = re.search(r'[ABCDE]', loan.get('credit_score', '') or '')
    cs_key = cs_match.group(0) if cs_match else 'N'

    ir_value = pw['IR'][loanAmountKey].get(ir_key, 0)
    rd_value = pw['RD'][loanAmountKey].get(rd_key, 0)
    w_type_coef = pw['w_type'][loanAmountKey].get(loan.get('nickname', ''), 1)
    dd_value = pw['DD'].get(dd_key, 0)
    cs_value = pw['CS'].get(cs_key, 0)

    # Global weights
    w = pw['w']
    coef = (
        ir_value * w['IR_score'] +
        rd_value * w['RD_score'] +
        dd_value * w['DD_score'] +
        cs_value * w['CS_score']
    )
    # Business weight
    w_business = pw['w_business'].get(loan.get('nickname', ''), 1)

    # Final score
    # loan['w_IR_score'] = w['IR_score']
    # loan['ir_value'] = ir_value
    # loan['w_RD_score'] = w['RD_score']
    # loan['rd_value'] = rd_value
    # loan['w_DD_score'] = w['DD_score']
    # loan['dd_value'] = dd_value
    # loan['w_CS_score'] = w['CS_score']
    # loan['cs_value'] = cs_value
    
    # loan['w_type_coef'] = w_type_coef
    # loan['coef'] = coef
    # loan['w_business'] = w_business
    loan['sortOrder'] = coef * w_type_coef * w_business

In [77]:

def update_with_la(records: List[Dict[str, Any]], la: float) -> List[Dict[str, Any]]:
    """
    Given desired loan amount 'la', update each record's
    loan_amount, monthly_repayment, deposit_amount,
    then filter and return valid records.
    """
    for rec in records:
        # calculate monthly repayment
        r = rec.get('repayment_duration', 0)
        ir_monthly = rec.get('interest_rate', 0) / (12 * 100)
        num = la * ir_monthly * (1 + ir_monthly) ** r
        den = (1 + ir_monthly) ** r - 1
        rec['loan_amount'] = la
        rec['monthly_repayment'] = num / den   # change to Rial
        rec['deposit_amount'] = (la / rec.get('loan_coefficient', 1)) * 100
        calculate_sort_order(rec)

    def valid(rec: Dict[str, Any]) -> bool:
        max_dep = rec.get('maximum_deposit_amount')
        if max_dep and max_dep.lower() != 'nan':
            try:
                if rec.get('deposit_amount') > int(max_dep):
                    return False
            except ValueError:
                pass
        la_lim = rec.get('loan_amount_limit', float('inf'))
        min_la = rec.get('minimum_loan_amount', 0)
        return min_la <= rec.get('loan_amount') <= la_lim
    valid_records = [r for r in records if valid(r)]
    # return valid_records
    return sorted(valid_records, key=lambda x: x.get('sortOrder', 0), reverse=True)

In [78]:
# df_all = pd.DataFrame(_records)
# df_all.head()

In [79]:
# df = pd.DataFrame(update_with_la(_records, la = 700_000_000))
# df.head(15)

In [80]:
# len(update_with_la(_records, la = 700_000_000))

In [81]:
def update_with_da(records: List[Dict[str, Any]], da: float) -> List[Dict[str, Any]]:
    """
    Given deposit amount 'da', update each record's
    loan_amount, monthly_repayment, deposit_amount,
    then filter and return valid records.
    """
    for rec in records:
        coeff = rec.get('loan_coefficient', 0) / 100
        la = coeff * da
        r = rec.get('repayment_duration', 0)
        ir_monthly = rec.get('interest_rate', 0) / (12 * 100)
        num = la * ir_monthly * (1 + ir_monthly) ** r
        den = (1 + ir_monthly) ** r - 1
        rec['loan_amount'] = la
        rec['monthly_repayment'] = num / den  # change to Rial
        rec['deposit_amount'] = da
        calculate_sort_order(rec)

    def valid(rec: Dict[str, Any]) -> bool:
        max_dep = rec.get('maximum_deposit_amount')
        if max_dep and max_dep.lower() != 'nan':
            try:
                if rec.get('deposit_amount') > int(max_dep):
                    return False
            except ValueError:
                pass
        la_lim = rec.get('loan_amount_limit', float('inf'))
        min_la = rec.get('minimum_loan_amount', 0)
        return min_la <= rec.get('loan_amount') <= la_lim

    valid_records = [r for r in records if valid(r)]
    # Sort descending by sortOrder
    return sorted(valid_records, key=lambda x: x.get('sortOrder', 0), reverse=True)

In [82]:
# print(update_with_da(_records, da = 200_000_000))

In [83]:
# len(update_with_da(_records, da = 200_000_000))

In [84]:
def query_complex(
    scenarios: List[Dict[str, Any]],
    deposit_amount: Optional[float] = None,
    repayment_duration: Optional[int] = None,
    deposit_duration: Optional[int] = None,
    interest_rate: Optional[float] = None,
    credit_score: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Filter scenarios based on provided parameters.
    """
    matches = []
    for rec in scenarios:
        # deposit range: up to 1.6x
        cond_da = (deposit_amount is None or
                   rec.get('deposit_amount', 0) <= deposit_amount * 1.6)
        cond_rd = (repayment_duration is None or
                   rec.get('repayment_duration') == repayment_duration)
        cond_dep = (deposit_duration is None or
                    rec.get('deposit_duration') == deposit_duration)
        cond_ir = (interest_rate is None or
                   rec.get('interest_rate') == interest_rate)
        cs_field = rec.get('credit_score', '')
        cond_cs = (credit_score is None or
                   (credit_score in cs_field) or
                   (credit_score == 'N' and 'فاقد رتبه' in cs_field))
        if cond_da and cond_rd and cond_dep and cond_ir and cond_cs:
            matches.append(rec)
    return sorted(matches, key=lambda x: x.get('sortOrder', 0), reverse=True)

In [85]:

def get_query_params( _records, 
    deposit__amount: Optional[float] = None,
    repayment__duration: Optional[int] = None,
    deposit__duration: Optional[int] = None,
    interest__rate: Optional[float] = None,
    credit__score: Optional[str] = None,
    loan__amount: Optional[float] = None
) -> List[Dict[str, Any]]:   #Input values are Toman


    if loan__amount:
        scenarios = update_with_la(_records, loan__amount)
    elif deposit__amount and loan__amount is None:
        scenarios = update_with_da(_records, deposit__amount)
    else:
        scenarios = _records

    report = query_complex(
        scenarios,
        deposit_amount=deposit__amount,
        repayment_duration=repayment__duration,
        deposit_duration=deposit__duration,
        interest_rate=interest__rate,
        credit_score=credit__score
    )

    return report

In [86]:
result = get_query_params( _records, 
    loan__amount = 200_000_000,
    deposit__amount= None,
    repayment__duration = None,
    deposit__duration = None,
    interest__rate = 18,
    credit__score = None,
    )

In [87]:
len(result)

30

In [88]:
nickname_0 = result[0].get('nickname', 'نامشخص')
loan_amount_0 = int(result[0].get('loan_amount', 0) / 10_000_000)
monthly_repayment_0 = int(result[0].get('monthly_repayment', 0) // 10)
deposit_amount_0=int(result[0].get('deposit_amount', 0) / 10_000_000)
interest_rate_0=result[0].get('interest_rate', 0)
repayment_duration_0=result[0].get('repayment_duration', 0)
deposit_duration_0=result[0].get('deposit_duration', 0)
credit_score_0=result[0].get('credit_score', 'نامشخص')

In [89]:
result[0]

{'id': 42,
 'nickname': 'شایان',
 'package_name': 'شایان یک',
 'contract_type': 'مرابحه/جعاله',
 'granted_method': 'واریز به حساب',
 'loan_amount_limit': 3000000000,
 'deposit_duration': 3,
 'interest_rate': 18,
 'repayment_duration': 12,
 'loan_coefficient': 80,
 'credit_score': 'B',
 'minimum_deposit_amount': 'nan',
 'maximum_deposit_amount': '15000000000',
 'minimum_loan_amount': 100000000,
 'guarantee': 'بله',
 'receiving_channel': 'غیر حضوری/ حضوری',
 'loan_amount': 200000000,
 'monthly_repayment': 18335998.58124589,
 'deposit_amount': 250000000.0,
 'sortOrder': 0.044667}

In [90]:
msg_filter = f"""{loan_amount_0} میلیون تومان وام {nickname_0} با کارمزد {interest_rate_0} درصد،
 نیاز به {deposit_amount_0}  میلیون تومان سپرده {deposit_duration_0} ماهه،
 با اقساط {monthly_repayment_0}  تومان در {repayment_duration_0} ماه
 با رتبه اعتباری {credit_score_0}.
 """

In [91]:
print(msg_filter)

20 میلیون تومان وام شایان با کارمزد 18 درصد،
 نیاز به 25  میلیون تومان سپرده 3 ماهه،
 با اقساط 1833599  تومان در 12 ماه
 با رتبه اعتباری B.

In [92]:
11_612_920

11612920

In [93]:
pd.DataFrame(result).head(10)

,id,nickname,package_name,contract_type,granted_method,loan_amount_limit,deposit_duration,interest_rate,repayment_duration,loan_coefficient,credit_score,minimum_deposit_amount,maximum_deposit_amount,minimum_loan_amount,guarantee,receiving_channel,loan_amount,monthly_repayment,deposit_amount,sortOrder
0,42,شایان,شایان یک,مرابحه/جعاله,واریز به حساب,3000000000,3,18,12,80,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.500000e+08,0.044667
1,43,شایان,شایان یک,مرابحه,کارت اعتباری,3000000000,3,18,12,100,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.000000e+08,0.044667
2,10,شایان,شایان یک,مرابحه/جعاله,واریز به حساب,3000000000,3,18,12,80,A,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.500000e+08,0.041517
3,11,شایان,شایان یک,مرابحه,کارت اعتباری,3000000000,3,18,12,100,A,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.000000e+08,0.041517
4,54,شایان,شایان یک,مرابحه/جعاله,واریز به حساب,3000000000,6,18,12,170,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,1.176471e+08,0.040467
5,55,شایان,شایان یک,مرابحه,کارت اعتباری,3000000000,6,18,12,200,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,1.000000e+08,0.040467
6,57,شایان,شایان یک,مرابحه/جعاله,واریز به حساب,3000000000,6,18,24,75,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,9.984820e+06,2.666667e+08,0.040467
7,58,شایان,شایان یک,مرابحه,کارت اعتباری,3000000000,6,18,24,70,B,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,9.984820e+06,2.857143e+08,0.040467
8,71,شایان,شایان یک,مرابحه/جعاله,واریز به حساب,3000000000,3,18,12,70,C,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.857143e+08,0.039942
9,72,شایان,شایان یک,مرابحه,کارت اعتباری,3000000000,3,18,12,90,C,nan,15000000000,100000000,بله,غیر حضوری/ حضوری,200000000,1.833600e+07,2.222222e+08,0.039942

# Final version (Deployed V)

In [94]:
import pandas as pd
#------------------------------------
# pd.options.display.max_columns= None
# pd.options.display.max_colwidth= 2
pd.options.display.max_rows = None

#------------------------------------

In [95]:
import pandas as pd
import re
import json
from typing import List, Dict, Any, Optional

# Load parameter weights once
def _load_weights() -> Dict[str, Any]:
    with open('parameters_weights.json', 'r', encoding='utf-8') as f:
        return json.load(f)

_parameters_weights = _load_weights()



def calculate_sort_order(loan: Dict[str, Any]) -> None:
    
    coef_table = loan.get('loan_coefficient',0)
    
    # Determine bucket
    loanAmountKey = 'out_of_range'
    la = loan.get('loan_amount', 0)
    if la <= 500_000_000:
        loanAmountKey = '1-50'
    elif la <= 1_000_000_000:
        loanAmountKey = '50-100'
    elif la <= 1_500_000_000:
        loanAmountKey = '100-150'
    elif la <= 2_000_000_000:
        loanAmountKey = '150-200'
    elif la <= 2_500_000_000:
        loanAmountKey = '200-250'
    elif la <= 3_000_000_000:
        loanAmountKey = '250-300'

    pw = _parameters_weights
    # Extract individual weights
    ir_key = str(loan.get('interest_rate', ''))
    rd_key = str(loan.get('repayment_duration', ''))
    dd_key = str(loan.get('deposit_duration', ''))
    # CS: first A-E or N
    cs_match = re.search(r'[ABCDE]', loan.get('credit_score', '') or '')
    cs_key = cs_match.group(0) if cs_match else 'N'

    ir_value = pw['IR'][loanAmountKey].get(ir_key, 0)
    rd_value = pw['RD'][loanAmountKey].get(rd_key, 0)
    w_type_coef = pw['w_type'][loanAmountKey].get(loan.get('nickname', ''), 1)
    dd_value = pw['DD'].get(dd_key, 0)
    cs_value = pw['CS'].get(cs_key, 0)

    # Global weights
    w = pw['w']
    coef = (
        ir_value * w['IR_score'] +
        rd_value * w['RD_score'] +
        dd_value * w['DD_score'] +
        cs_value * w['CS_score']
    )
    # Business weight
    w_business = pw['w_business'].get(loan.get('nickname', ''), 1)
    # Calculate final score
    # loan['sortOrder'] = coef * w_type_coef * w_business
    loan['sortOrder'] = coef * w_type_coef * coef_table
    loan['pre_sortOrder'] = coef * w_type_coef 





def update_with_la(records: List[Dict[str, Any]], la: float) -> List[Dict[str, Any]]:
    """
    Given desired loan amount 'la', update each record's
    loan_amount, monthly_repayment, deposit_amount,
    then filter and return valid records.
    """
    for rec in records:
        # calculate monthly repayment
        r = rec.get('repayment_duration', 0)
        ir_monthly = rec.get('interest_rate', 0) / (12 * 100)
        num = la * ir_monthly * (1 + ir_monthly) ** r
        den = (1 + ir_monthly) ** r - 1
        rec['loan_amount'] = la
        rec['monthly_repayment'] = num / den   # change to Rial
        rec['deposit_amount'] = (la / rec.get('loan_coefficient', 1)) * 100
        calculate_sort_order(rec)

    def valid(rec: Dict[str, Any]) -> bool:
        max_dep = rec.get('maximum_deposit_amount')
        if max_dep and max_dep.lower() != 'nan':
            try:
                if rec.get('deposit_amount') > int(max_dep):
                    return False
            except ValueError:
                pass
        la_lim = rec.get('loan_amount_limit', float('inf'))
        min_la = rec.get('minimum_loan_amount', 0)
        return min_la <= rec.get('loan_amount') <= la_lim
    valid_records = [r for r in records if valid(r)]
    # return valid_records
    return sorted(valid_records, key=lambda x: x.get('sortOrder', 0), reverse=True)


def update_with_da(records: List[Dict[str, Any]], da: float) -> List[Dict[str, Any]]:
    """
    Given deposit amount 'da', update each record's
    loan_amount, monthly_repayment, deposit_amount,
    then filter and return valid records.
    """
    for rec in records:
        coeff = rec.get('loan_coefficient', 0) / 100
        la = coeff * da
        r = rec.get('repayment_duration', 0)
        ir_monthly = rec.get('interest_rate', 0) / (12 * 100)
        num = la * ir_monthly * (1 + ir_monthly) ** r
        den = (1 + ir_monthly) ** r - 1
        rec['loan_amount'] = la
        rec['monthly_repayment'] = num / den  # change to Rial
        rec['deposit_amount'] = da
        calculate_sort_order(rec)

    def valid(rec: Dict[str, Any]) -> bool:
        max_dep = rec.get('maximum_deposit_amount')
        if max_dep and max_dep.lower() != 'nan':
            try:
                if rec.get('deposit_amount') > int(max_dep):
                    return False
            except ValueError:
                pass
        la_lim = rec.get('loan_amount_limit', float('inf'))
        min_la = rec.get('minimum_loan_amount', 0)
        return min_la <= rec.get('loan_amount') <= la_lim

    valid_records = [r for r in records if valid(r)]
    # Sort descending by sortOrder
    return sorted(valid_records, key=lambda x: x.get('sortOrder', 0), reverse=True)



def query_complex(
    scenarios: List[Dict[str, Any]],
    deposit_amount: Optional[float] = None,
    repayment_duration: Optional[int] = None,
    deposit_duration: Optional[int] = None,
    interest_rate: Optional[float] = None,
    credit_score: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Filter scenarios based on provided parameters.
    """
    matches = []
    for rec in scenarios:
        # deposit range: up to 1.6x
        cond_da = (deposit_amount is None or
                   rec.get('deposit_amount', 0) <= deposit_amount * 1.6)
        cond_rd = (repayment_duration is None or
                   rec.get('repayment_duration') == repayment_duration)
        cond_dep = (deposit_duration is None or
                    rec.get('deposit_duration') == deposit_duration)
        cond_ir = (interest_rate is None or
                   rec.get('interest_rate') == interest_rate)
        cs_field = rec.get('credit_score', '')
        cond_cs = (credit_score is None or
                   (credit_score in cs_field) or
                   (credit_score == 'N' and 'فاقد رتبه' in cs_field))
        if cond_da and cond_rd and cond_dep and cond_ir and cond_cs:
            matches.append(rec)
    return sorted(matches, key=lambda x: x.get('sortOrder', 0), reverse=True)

In [96]:
import json
from typing import List, Dict, Any, Optional

# Load parameter weights once
def load_record() -> Dict[str, Any]:
    with open('MEC-LoanRecomn_Scenarios-V16.json', 'r', encoding='utf-8') as f:
        return json.load(f)

_records = load_record()



def get_query_params( _records, 
    deposit__amount: Optional[float] = None,
    repayment__duration: Optional[int] = None,
    deposit__duration: Optional[int] = None,
    interest__rate: Optional[float] = None,
    credit__score: Optional[str] = None,
    loan__amount: Optional[float] = None
) -> List[Dict[str, Any]]:   #Input values are Toman


    if loan__amount:
        scenarios = update_with_la(_records, loan__amount)
    elif deposit__amount and loan__amount is None:
        scenarios = update_with_da(_records, deposit__amount)
    else:
        scenarios = _records

    report = query_complex(
        scenarios,
        deposit_amount=deposit__amount,
        repayment_duration=repayment__duration,
        deposit_duration=deposit__duration,
        interest_rate=interest__rate,
        credit_score=credit__score
    )

    

    # msg= f"تعداد {len(report)} پیشنهاد وام برای شما پیدا شد.\n\n"
    loan_number = len(report)
    return report, loan_number

In [97]:
result , number = get_query_params( _records, 
    loan__amount = 1_000_000_000,
    deposit__amount= None,
    repayment__duration = None,
    deposit__duration = None,
    interest__rate = None,
    credit__score = None,
    )

In [98]:
print(number)

159

In [99]:
df_new = pd.DataFrame(result)

In [100]:
df_reduced = df_new.drop(["granted_method","loan_amount_limit","maximum_deposit_amount","minimum_deposit_amount","minimum_loan_amount","guarantee","receiving_channel","contract_type","package_name"], axis = 1)

In [101]:
df_reduced

,id,nickname,deposit_duration,interest_rate,repayment_duration,loan_coefficient,credit_score,loan_amount,monthly_repayment,deposit_amount,sortOrder,pre_sortOrder
0,2,بهان(بدون ضامن),3,23,60,1000,B,1000000000,2.819047e+07,1.000000e+08,101.67000,0.101670
1,1,بهان(بدون ضامن),3,23,60,1000,A,1000000000,2.819047e+07,1.000000e+08,97.17000,0.097170
2,101,فرابانک,3,23,36,1000,B,1000000000,3.870972e+07,1.000000e+08,61.36200,0.061362
3,100,فرابانک,3,23,36,1000,A,1000000000,3.870972e+07,1.000000e+08,58.66200,0.058662
4,102,فرابانک,3,23,36,1000,C,1000000000,3.870972e+07,1.000000e+08,57.31200,0.057312
5,45,شایان,3,23,12,450,B,1000000000,9.407632e+07,2.222222e+08,26.96490,0.059922
6,13,شایان,3,23,12,450,A,1000000000,9.407632e+07,2.222222e+08,25.74990,0.057222
7,137,نیک‌وام,12,4,12,320,B,1000000000,8.514990e+07,3.125000e+08,22.84800,0.071400
8,118,نیک‌وام,12,4,12,320,A,1000000000,8.514990e+07,3.125000e+08,21.21600,0.066300
9,156,نیک‌وام,12,4,12,320,C,1000000000,8.514990e+07,3.125000e+08,20.40000,0.063750
10,37,شایان,2,23,12,300,B,1000000000,9.407632e+07,3.333333e+08,17.97660,0.059922
11,5,شایان,2,23,12,300,A,1000000000,9.407632e+07,3.333333e+08,17.16660,0.057222
12,74,شایان,3,23,12,300,C,1000000000,9.407632e+07,3.333333e+08,16.76160,0.055872
13,44,شایان,3,23,12,200,B,1000000000,9.407632e+07,5.000000e+08,11.98440,0.059922
14,138,نیک‌وام,12,4,24,160,B,1000000000,4.342492e+07,6.250000e+08,11.64160,0.072760
15,12,شایان,3,23,12,200,A,1000000000,9.407632e+07,5.000000e+08,11.44440,0.057222
16,133,نیک‌وام,6,4,12,160,B,1000000000,8.514990e+07,6.250000e+08,11.42400,0.071400
17,60,شایان,6,23,24,200,B,1000000000,5.237331e+07,5.000000e+08,11.40840,0.057042
18,68,شایان,2,23,12,200,C,1000000000,9.407632e+07,5.000000e+08,11.17440,0.055872
19,28,شایان,6,23,24,200,A,1000000000,5.237331e+07,5.000000e+08,10.86840,0.054342
20,119,نیک‌وام,12,4,24,160,A,1000000000,4.342492e+07,6.250000e+08,10.82560,0.067660
21,114,نیک‌وام,6,4,12,160,A,1000000000,8.514990e+07,6.250000e+08,10.60800,0.066300
22,157,نیک‌وام,12,4,24,160,C,1000000000,4.342492e+07,6.250000e+08,10.41760,0.065110
23,152,نیک‌وام,6,4,12,160,C,1000000000,8.514990e+07,6.250000e+08,10.20000,0.063750
24,73,شایان,3,23,12,175,C,1000000000,9.407632e+07,5.714286e+08,9.77760,0.055872
25,36,شایان,2,23,12,150,B,1000000000,9.407632e+07,6.666667e+08,8.98830,0.059922
26,4,شایان,2,23,12,150,A,1000000000,9.407632e+07,6.666667e+08,8.58330,0.057222
27,59,شایان,6,23,24,150,B,1000000000,5.237331e+07,6.666667e+08,8.55630,0.057042
28,129,نیک‌وام,4,4,12,110,B,1000000000,8.514990e+07,9.090909e+08,8.22800,0.074800
29,139,نیک‌وام,12,4,36,110,B,1000000000,2.952399e+07,9.090909e+08,8.15320,0.074120
30,27,شایان,6,23,24,150,A,1000000000,5.237331e+07,6.666667e+08,8.15130,0.054342
31,86,شایان,6,23,24,150,C,1000000000,5.237331e+07,6.666667e+08,7.94880,0.052992
32,110,نیک‌وام,4,4,12,110,A,1000000000,8.514990e+07,9.090909e+08,7.66700,0.069700
33,120,نیک‌وام,12,4,36,110,A,1000000000,2.952399e+07,9.090909e+08,7.59220,0.069020
34,148,نیک‌وام,4,4,12,110,C,1000000000,8.514990e+07,9.090909e+08,7.38650,0.067150
35,158,نیک‌وام,12,4,36,110,C,1000000000,2.952399e+07,9.090909e+08,7.31170,0.066470
36,64,شایان,6,23,36,125,B,1000000000,3.870972e+07,8.000000e+08,7.22025,0.057762
37,32,شایان,6,23,36,125,A,1000000000,3.870972e+07,8.000000e+08,6.88275,0.055062
38,67,شایان,2,23,12,120,C,1000000000,9.407632e+07,8.333333e+08,6.70464,0.055872
39,85,شایان,6,23,24,125,C,1000000000,5.237331e+07,8.000000e+08,6.62400,0.052992
40,63,شایان,6,23,36,110,B,1000000000,3.870972e+07,9.090909e+08,6.35382,0.057762
41,47,شایان,3,23,24,100,B,1000000000,5.237331e+07,1.000000e+09,6.06420,0.060642
42,31,شایان,6,23,36,110,A,1000000000,3.870972e+07,9.090909e+08,6.05682,0.055062
43,134,نیک‌وام,6,4,24,80,B,1000000000,4.342492e+07,1.250000e+09,5.82080,0.072760
44,15,شایان,3,23,24,100,A,1000000000,5.237331e+07,1.000000e+09,5.79420,0.057942
45,55,شایان,6,18,12,200,B,1000000000,9.167999e+07,5.000000e+08,5.73480,0.028674
46,90,شایان,3,23,12,110,D,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822
47,95,شایان,3,23,12,110,E,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822
48,115,نیک‌وام,6,4,24,80,A,1000000000,4.342492e+07,1.250000e+09,5.41280,0.067660
49,89,شایان,6,23,36,100,C,1000000000,3.870972e+07,1.000000e+09,5.37120,0.053712
50,140,نیک‌وام,12,4,48,80,B,1000000000,2.257905e+07,1.250000e+09,5.22240,0.065280
51,153,نیک‌وام,6,4,24,80,C,1000000000,4.342492e+07,1.250000e+09,5.20880,0.065110
52,23,شایان,6,18,12,200,A,1000000000,9.167999e+07,5.000000e+08,5.19480,0.025974
53,93,شایان,6,23,24,100,D,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942
54,98,شایان,6,23,24,100,E,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942
55,54,شایان,6,18,12,170,B,1000000000,9.167999e+07,5.882353e+08,4.87458,0.028674
56,46,شایان,3,23,24,80,B,1000000000,5.237331e+07,1.250000e+09,4.85136,0.060642
57,88,شایان,6,23,36,90,C,1000000000,3.870972e+07,1.111111e+09,4.83408,0.053712
58,121,نیک‌وام,12,4,48,80,A,1000000000,2.257905e+07,1.250000e+09,4.81440,0.060180
59,66,شایان,6,23,48,90,B,1000000000,3.205147e+07,1.111111e+09,4.77738,0.053082
60,14,شایان,3,23,24,80,A,1000000000,5.237331e+07,1.250000e+09,4.63536,0.057942
61,159,نیک‌وام,12,4,48,80,C,1000000000,2.257905e+07,1.250000e+09,4.61040,0.057630
62,34,شایان,6,23,48,90,A,1000000000,3.205147e+07,1.111111e+09,4.53438,0.050382
63,76,شایان,3,23,24,80,C,1000000000,5.237331e+07,1.250000e+09,4.52736,0.056592
64,135,نیک‌وام,6,4,36,60,B,1000000000,2.952399e+07,1.666667e+09,4.44720,0.074120
65,82,شایان,6,18,12,180,C,1000000000,9.167999e+07,5.555556e+08,4.43232,0.024624
66,22,شایان,6,18,12,170,A,1000000000,9.167999e+07,5.882353e+08,4.41558,0.025974
67,125,نیک‌وام,2,4,12,55,B,1000000000,8.514990e+07,1.818182e+09,4.30100,0.078200
68,130,نیک‌وام,4,4,24,55,B,1000000000,4.342492e+07,1.818182e+09,4.18880,0.076160
69,116,نیک‌وام,6,4,36,60,A,1000000000,2.952399e+07,1.666667e+09,4.14120,0.069020
70,106,نیک‌وام,2,4,12,55,A,1000000000,8.514990e+07,1.818182e+09,4.02050,0.073100
71,154,نیک‌وام,6,4,36,60,C,1000000000,2.952399e+07,1.666667e+09,3.98820,0.066470
72,65,شایان,6,23,48,75,B,1000000000,3.205147e+07,1.333333e+09,3.98115,0.053082
73,75,شایان,3,23,24,70,C,1000000000,5.237331e+07,1.428571e+09,3.96144,0.056592
74,111,نیک‌وام,4,4,24,55,A,1000000000,4.342492e+07,1.818182e+09,3.90830,0.071060
75,144,نیک‌وام,2,4,12,55,C,1000000000,8.514990e+07,1.818182e+09,3.88025,0.070550
76,33,شایان,6,23,48,75,A,1000000000,3.205147e+07,1.333333e+09,3.77865,0.050382
77,149,نیک‌وام,4,4,24,55,C,1000000000,4.342492e+07,1.818182e+09,3.76805,0.068510
78,81,شایان,6,18,12,150,C,1000000000,9.167999e+07,6.666667e+08,3.69360,0.024624
79,49,شایان,3,23,36,60,B,1000000000,3.870972e+07,1.666667e+09,3.68172,0.061362
80,39,شایان,2,23,24,60,B,1000000000,5.237331e+07,1.666667e+09,3.63852,0.060642
81,17,شایان,3,23,36,60,A,1000000000,3.870972e+07,1.666667e+09,3.51972,0.058662
82,7,شایان,2,23,24,60,A,1000000000,5.237331e+07,1.666667e+09,3.47652,0.057942
83,94,شایان,6,23,36,70,D,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662
84,99,شایان,6,23,36,70,E,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662
85,38,شایان,2,23,24,55,B,1000000000,5.237331e+07,1.818182e+09,3.33531,0.060642
86,43,شایان,3,18,12,100,B,1000000000,9.167999e+07,1.000000e+09,3.22740,0.032274
87,6,شایان,2,23,24,55,A,1000000000,5.237331e+07,1.818182e+09,3.18681,0.057942
88,53,شایان,6,14,12,110,B,1000000000,8.978712e+07,9.090909e+08,3.14820,0.028620
89,131,نیک‌وام,4,4,36,40,B,1000000000,2.952399e+07,2.500000e+09,3.10080,0.077520
90,35,شایان,1,23,12,50,B,1000000000,9.407632e+07,2.000000e+09,3.08610,0.061722
91,48,شایان,3,23,36,50,B,1000000000,3.870972e+07,2.000000e+09,3.06810,0.061362
92,11,شایان,3,18,12,100,A,1000000000,9.167999e+07,1.000000e+09,2.95740,0.029574
93,3,شایان,1,23,12,50,A,1000000000,9.407632e+07,2.000000e+09,2.95110,0.059022
94,136,نیک‌وام,6,4,48,45,B,1000000000,2.257905e+07,2.222222e+09,2.93760,0.065280
95,16,شایان,3,23,36,50,A,1000000000,3.870972e+07,2.000000e+09,2.93310,0.058662
96,112,نیک‌وام,4,4,36,40,A,1000000000,2.952399e+07,2.500000e+09,2.89680,0.072420
97,78,شایان,3,23,36,50,C,1000000000,3.870972e+07,2.000000e+09,2.86560,0.057312
98,21,شایان,6,14,12,110,A,1000000000,8.978712e+07,9.090909e+08,2.85120,0.025920
99,70,شایان,2,23,24,50,C,1000000000,5.237331e+07,2.000000e+09,2.82960,0.056592
100,150,نیک‌وام,4,4,36,40,C,1000000000,2.952399e+07,2.500000e+09,2.79480,0.069870
101,117,نیک‌وام,6,4,48,45,A,1000000000,2.257905e+07,2.222222e+09,2.70810,0.060180
102,155,نیک‌وام,6,4,48,45,C,1000000000,2.257905e+07,2.222222e+09,2.59335,0.057630
103,42,شایان,3,18,12,80,B,1000000000,9.167999e+07,1.250000e+09,2.58192,0.032274
104,52,شایان,6,14,12,90,B,1000000000,8.978712e+07,1.111111e+09,2.57580,0.028620
105,69,شایان,2,23,24,45,C,1000000000,5.237331e+07,2.222222e+09,2.54664,0.056592
106,72,شایان,3,18,12,90,C,1000000000,9.167999e+07,1.111111e+09,2.54016,0.028224
107,126,نیک‌وام,2,4,24,30,B,1000000000,4.342492e+07,3.333333e+09,2.38680,0.079560
108,10,شایان,3,18,12,80,A,1000000000,9.167999e+07,1.250000e+09,2.36592,0.029574
109,91,شایان,3,23,24,45,D,1000000000,5.237331e+07,2.222222e+09,2.36439,0.052542
110,96,شایان,3,23,24,45,E,1000000000,5.237331e+07,2.222222e+09,2.36439,0.052542
111,20,شایان,6,14,12,90,A,1000000000,8.978712e+07,1.111111e+09,2.33280,0.025920
112,77,شایان,3,23,36,40,C,1000000000,3.870972e+07,2.500000e+09,2.29248,0.057312
113,107,نیک‌وام,2,4,24,30,A,1000000000,4.342492e+07,3.333333e+09,2.23380,0.074460
114,80,شایان,6,14,12,90,C,1000000000,8.978712e+07,1.111111e+09,2.21130,0.024570
115,57,شایان,6,18,24,75,B,1000000000,4.992410e+07,1.333333e+09,2.20455,0.029394
116,122,نیک‌وام,1,4,12,27,B,1000000000,8.514990e+07,3.703704e+09,2.20320,0.081600
117,145,نیک‌وام,2,4,24,30,C,1000000000,4.342492e+07,3.333333e+09,2.15730,0.071910
118,41,شایان,2,23,36,35,B,1000000000,3.870972e+07,2.857143e+09,2.14767,0.061362
119,103,نیک‌وام,1,4,12,27,A,1000000000,8.514990e+07,3.703704e+09,2.06550,0.076500
120,132,نیک‌وام,4,4,48,30,B,1000000000,2.257905e+07,3.333333e+09,2.06040,0.068680
121,58,شایان,6,18,24,70,B,1000000000,4.992410e+07,1.428571e+09,2.05758,0.029394
122,9,شایان,2,23,36,35,A,1000000000,3.870972e+07,2.857143e+09,2.05317,0.058662
123,25,شایان,6,18,24,75,A,1000000000,4.992410e+07,1.333333e+09,2.00205,0.026694
124,141,نیک‌وام,1,4,12,27,C,1000000000,8.514990e+07,3.703704e+09,1.99665,0.073950
125,51,شایان,3,23,48,35,B,1000000000,3.205147e+07,2.857143e+09,1.98387,0.056682
126,71,شایان,3,18,12,70,C,1000000000,9.167999e+07,1.428571e+09,1.97568,0.028224
127,113,نیک‌وام,4,4,48,30,A,1000000000,2.257905e+07,3.333333e+09,1.90740,0.063580
128,19,شایان,3,23,48,35,A,1000000000,3.205147e+07,2.857143e+09,1.88937,0.053982
129,26,شایان,6,18,24,70,A,1000000000,4.992410e+07,1.428571e+09,1.86858,0.026694
130,79,شایان,6,14,12,75,C,1000000000,8.978712e+07,1.333333e+09,1.84275,0.024570
131,40,شایان,2,23,36,30,B,1000000000,3.870972e+07,3.333333e+09,1.84086,0.061362
132,151,نیک‌وام,4,4,48,30,C,1000000000,2.257905e+07,3.333333e+09,1.83090,0.061030
133,8,شایان,2,23,36,30,A,1000000000,3.870972e+07,3.333333e+09,1.75986,0.058662
134,50,شایان,3,23,48,30,B,1000000000,3.205147e+07,3.333333e+09,1.70046,0.056682
135,18,شایان,3,23,48,30,A,1000000000,3.205147e+07,3.333333e+09,1.61946,0.053982
136,127,نیک‌وام,2,4,36,20,B,1000000000,2.952399e+07,5.000000e+09,1.61840,0.080920
137,92,شایان,3,23,36,30,D,1000000000,3.870972e+07,3.333333e+09,1.59786,0.053262
138,97,شایان,3,23,36,30,E,1000000000,3.870972e+07,3.333333e+09,1.59786,0.053262
139,83,شایان,6,18,24,60,C,1000000000,4.992410e+07,1.666667e+09,1.52064,0.025344
140,108,نیک‌وام,2,4,36,20,A,1000000000,2.952399e+07,5.000000e+09,1.51640,0.075820
141,61,شایان,6,18,36,50,B,1000000000,3.615240e+07,2.000000e+09,1.50570,0.030114
142,146,نیک‌وام,2,4,36,20,C,1000000000,2.952399e+07,5.000000e+09,1.46540,0.073270
143,84,شایان,6,18,24,55,C,1000000000,4.992410e+07,1.818182e+09,1.39392,0.025344
144,29,شایان,6,18,36,50,A,1000000000,3.615240e+07,2.000000e+09,1.37070,0.027414
145,62,شایان,6,18,36,45,B,1000000000,3.615240e+07,2.222222e+09,1.35513,0.030114
146,56,شایان,6,14,24,45,B,1000000000,4.801288e+07,2.222222e+09,1.32030,0.029340
147,123,نیک‌وام,1,4,24,15,B,1000000000,4.342492e+07,6.666667e+09,1.24440,0.082960
148,30,شایان,6,18,36,45,A,1000000000,3.615240e+07,2.222222e+09,1.23363,0.027414
149,24,شایان,6,14,24,45,A,1000000000,4.801288e+07,2.222222e+09,1.19880,0.026640
150,104,نیک‌وام,1,4,24,15,A,1000000000,4.342492e+07,6.666667e+09,1.16790,0.077860
151,142,نیک‌وام,1,4,24,15,C,1000000000,4.342492e+07,6.666667e+09,1.12965,0.075310
152,128,نیک‌وام,2,4,48,15,B,1000000000,2.257905e+07,6.666667e+09,1.08120,0.072080
153,87,شایان,6,18,36,40,C,1000000000,3.615240e+07,2.500000e+09,1.04256,0.026064
154,109,نیک‌وام,2,4,48,15,A,1000000000,2.257905e+07,6.666667e+09,1.00470,0.066980
155,147,نیک‌وام,2,4,48,15,C,1000000000,2.257905e+07,6.666667e+09,0.96645,0.064430
156,124,نیک‌وام,1,4,36,10,B,1000000000,2.952399e+07,1.000000e+10,0.84320,0.084320
157,105,نیک‌وام,1,4,36,10,A,1000000000,2.952399e+07,1.000000e+10,0.79220,0.079220
158,143,نیک‌وام,1,4,36,10,C,1000000000,2.952399e+07,1.000000e+10,0.76670,0.076670

In [102]:
df_reduced ["coef_sort"]=df_reduced["loan_coefficient"]*df_reduced["pre_sortOrder"]

In [103]:
df_reduced.head(100)

,id,nickname,deposit_duration,interest_rate,repayment_duration,loan_coefficient,credit_score,loan_amount,monthly_repayment,deposit_amount,sortOrder,pre_sortOrder,coef_sort
0,2,بهان(بدون ضامن),3,23,60,1000,B,1000000000,2.819047e+07,1.000000e+08,101.67000,0.101670,101.67000
1,1,بهان(بدون ضامن),3,23,60,1000,A,1000000000,2.819047e+07,1.000000e+08,97.17000,0.097170,97.17000
2,101,فرابانک,3,23,36,1000,B,1000000000,3.870972e+07,1.000000e+08,61.36200,0.061362,61.36200
3,100,فرابانک,3,23,36,1000,A,1000000000,3.870972e+07,1.000000e+08,58.66200,0.058662,58.66200
4,102,فرابانک,3,23,36,1000,C,1000000000,3.870972e+07,1.000000e+08,57.31200,0.057312,57.31200
5,45,شایان,3,23,12,450,B,1000000000,9.407632e+07,2.222222e+08,26.96490,0.059922,26.96490
6,13,شایان,3,23,12,450,A,1000000000,9.407632e+07,2.222222e+08,25.74990,0.057222,25.74990
7,137,نیک‌وام,12,4,12,320,B,1000000000,8.514990e+07,3.125000e+08,22.84800,0.071400,22.84800
8,118,نیک‌وام,12,4,12,320,A,1000000000,8.514990e+07,3.125000e+08,21.21600,0.066300,21.21600
9,156,نیک‌وام,12,4,12,320,C,1000000000,8.514990e+07,3.125000e+08,20.40000,0.063750,20.40000
10,37,شایان,2,23,12,300,B,1000000000,9.407632e+07,3.333333e+08,17.97660,0.059922,17.97660
11,5,شایان,2,23,12,300,A,1000000000,9.407632e+07,3.333333e+08,17.16660,0.057222,17.16660
12,74,شایان,3,23,12,300,C,1000000000,9.407632e+07,3.333333e+08,16.76160,0.055872,16.76160
13,44,شایان,3,23,12,200,B,1000000000,9.407632e+07,5.000000e+08,11.98440,0.059922,11.98440
14,138,نیک‌وام,12,4,24,160,B,1000000000,4.342492e+07,6.250000e+08,11.64160,0.072760,11.64160
15,12,شایان,3,23,12,200,A,1000000000,9.407632e+07,5.000000e+08,11.44440,0.057222,11.44440
16,133,نیک‌وام,6,4,12,160,B,1000000000,8.514990e+07,6.250000e+08,11.42400,0.071400,11.42400
17,60,شایان,6,23,24,200,B,1000000000,5.237331e+07,5.000000e+08,11.40840,0.057042,11.40840
18,68,شایان,2,23,12,200,C,1000000000,9.407632e+07,5.000000e+08,11.17440,0.055872,11.17440
19,28,شایان,6,23,24,200,A,1000000000,5.237331e+07,5.000000e+08,10.86840,0.054342,10.86840
20,119,نیک‌وام,12,4,24,160,A,1000000000,4.342492e+07,6.250000e+08,10.82560,0.067660,10.82560
21,114,نیک‌وام,6,4,12,160,A,1000000000,8.514990e+07,6.250000e+08,10.60800,0.066300,10.60800
22,157,نیک‌وام,12,4,24,160,C,1000000000,4.342492e+07,6.250000e+08,10.41760,0.065110,10.41760
23,152,نیک‌وام,6,4,12,160,C,1000000000,8.514990e+07,6.250000e+08,10.20000,0.063750,10.20000
24,73,شایان,3,23,12,175,C,1000000000,9.407632e+07,5.714286e+08,9.77760,0.055872,9.77760
25,36,شایان,2,23,12,150,B,1000000000,9.407632e+07,6.666667e+08,8.98830,0.059922,8.98830
26,4,شایان,2,23,12,150,A,1000000000,9.407632e+07,6.666667e+08,8.58330,0.057222,8.58330
27,59,شایان,6,23,24,150,B,1000000000,5.237331e+07,6.666667e+08,8.55630,0.057042,8.55630
28,129,نیک‌وام,4,4,12,110,B,1000000000,8.514990e+07,9.090909e+08,8.22800,0.074800,8.22800
29,139,نیک‌وام,12,4,36,110,B,1000000000,2.952399e+07,9.090909e+08,8.15320,0.074120,8.15320
30,27,شایان,6,23,24,150,A,1000000000,5.237331e+07,6.666667e+08,8.15130,0.054342,8.15130
31,86,شایان,6,23,24,150,C,1000000000,5.237331e+07,6.666667e+08,7.94880,0.052992,7.94880
32,110,نیک‌وام,4,4,12,110,A,1000000000,8.514990e+07,9.090909e+08,7.66700,0.069700,7.66700
33,120,نیک‌وام,12,4,36,110,A,1000000000,2.952399e+07,9.090909e+08,7.59220,0.069020,7.59220
34,148,نیک‌وام,4,4,12,110,C,1000000000,8.514990e+07,9.090909e+08,7.38650,0.067150,7.38650
35,158,نیک‌وام,12,4,36,110,C,1000000000,2.952399e+07,9.090909e+08,7.31170,0.066470,7.31170
36,64,شایان,6,23,36,125,B,1000000000,3.870972e+07,8.000000e+08,7.22025,0.057762,7.22025
37,32,شایان,6,23,36,125,A,1000000000,3.870972e+07,8.000000e+08,6.88275,0.055062,6.88275
38,67,شایان,2,23,12,120,C,1000000000,9.407632e+07,8.333333e+08,6.70464,0.055872,6.70464
39,85,شایان,6,23,24,125,C,1000000000,5.237331e+07,8.000000e+08,6.62400,0.052992,6.62400
40,63,شایان,6,23,36,110,B,1000000000,3.870972e+07,9.090909e+08,6.35382,0.057762,6.35382
41,47,شایان,3,23,24,100,B,1000000000,5.237331e+07,1.000000e+09,6.06420,0.060642,6.06420
42,31,شایان,6,23,36,110,A,1000000000,3.870972e+07,9.090909e+08,6.05682,0.055062,6.05682
43,134,نیک‌وام,6,4,24,80,B,1000000000,4.342492e+07,1.250000e+09,5.82080,0.072760,5.82080
44,15,شایان,3,23,24,100,A,1000000000,5.237331e+07,1.000000e+09,5.79420,0.057942,5.79420
45,55,شایان,6,18,12,200,B,1000000000,9.167999e+07,5.000000e+08,5.73480,0.028674,5.73480
46,90,شایان,3,23,12,110,D,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822,5.70042
47,95,شایان,3,23,12,110,E,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822,5.70042
48,115,نیک‌وام,6,4,24,80,A,1000000000,4.342492e+07,1.250000e+09,5.41280,0.067660,5.41280
49,89,شایان,6,23,36,100,C,1000000000,3.870972e+07,1.000000e+09,5.37120,0.053712,5.37120
50,140,نیک‌وام,12,4,48,80,B,1000000000,2.257905e+07,1.250000e+09,5.22240,0.065280,5.22240
51,153,نیک‌وام,6,4,24,80,C,1000000000,4.342492e+07,1.250000e+09,5.20880,0.065110,5.20880
52,23,شایان,6,18,12,200,A,1000000000,9.167999e+07,5.000000e+08,5.19480,0.025974,5.19480
53,93,شایان,6,23,24,100,D,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942,4.89420
54,98,شایان,6,23,24,100,E,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942,4.89420
55,54,شایان,6,18,12,170,B,1000000000,9.167999e+07,5.882353e+08,4.87458,0.028674,4.87458
56,46,شایان,3,23,24,80,B,1000000000,5.237331e+07,1.250000e+09,4.85136,0.060642,4.85136
57,88,شایان,6,23,36,90,C,1000000000,3.870972e+07,1.111111e+09,4.83408,0.053712,4.83408
58,121,نیک‌وام,12,4,48,80,A,1000000000,2.257905e+07,1.250000e+09,4.81440,0.060180,4.81440
59,66,شایان,6,23,48,90,B,1000000000,3.205147e+07,1.111111e+09,4.77738,0.053082,4.77738
60,14,شایان,3,23,24,80,A,1000000000,5.237331e+07,1.250000e+09,4.63536,0.057942,4.63536
61,159,نیک‌وام,12,4,48,80,C,1000000000,2.257905e+07,1.250000e+09,4.61040,0.057630,4.61040
62,34,شایان,6,23,48,90,A,1000000000,3.205147e+07,1.111111e+09,4.53438,0.050382,4.53438
63,76,شایان,3,23,24,80,C,1000000000,5.237331e+07,1.250000e+09,4.52736,0.056592,4.52736
64,135,نیک‌وام,6,4,36,60,B,1000000000,2.952399e+07,1.666667e+09,4.44720,0.074120,4.44720
65,82,شایان,6,18,12,180,C,1000000000,9.167999e+07,5.555556e+08,4.43232,0.024624,4.43232
66,22,شایان,6,18,12,170,A,1000000000,9.167999e+07,5.882353e+08,4.41558,0.025974,4.41558
67,125,نیک‌وام,2,4,12,55,B,1000000000,8.514990e+07,1.818182e+09,4.30100,0.078200,4.30100
68,130,نیک‌وام,4,4,24,55,B,1000000000,4.342492e+07,1.818182e+09,4.18880,0.076160,4.18880
69,116,نیک‌وام,6,4,36,60,A,1000000000,2.952399e+07,1.666667e+09,4.14120,0.069020,4.14120
70,106,نیک‌وام,2,4,12,55,A,1000000000,8.514990e+07,1.818182e+09,4.02050,0.073100,4.02050
71,154,نیک‌وام,6,4,36,60,C,1000000000,2.952399e+07,1.666667e+09,3.98820,0.066470,3.98820
72,65,شایان,6,23,48,75,B,1000000000,3.205147e+07,1.333333e+09,3.98115,0.053082,3.98115
73,75,شایان,3,23,24,70,C,1000000000,5.237331e+07,1.428571e+09,3.96144,0.056592,3.96144
74,111,نیک‌وام,4,4,24,55,A,1000000000,4.342492e+07,1.818182e+09,3.90830,0.071060,3.90830
75,144,نیک‌وام,2,4,12,55,C,1000000000,8.514990e+07,1.818182e+09,3.88025,0.070550,3.88025
76,33,شایان,6,23,48,75,A,1000000000,3.205147e+07,1.333333e+09,3.77865,0.050382,3.77865
77,149,نیک‌وام,4,4,24,55,C,1000000000,4.342492e+07,1.818182e+09,3.76805,0.068510,3.76805
78,81,شایان,6,18,12,150,C,1000000000,9.167999e+07,6.666667e+08,3.69360,0.024624,3.69360
79,49,شایان,3,23,36,60,B,1000000000,3.870972e+07,1.666667e+09,3.68172,0.061362,3.68172
80,39,شایان,2,23,24,60,B,1000000000,5.237331e+07,1.666667e+09,3.63852,0.060642,3.63852
81,17,شایان,3,23,36,60,A,1000000000,3.870972e+07,1.666667e+09,3.51972,0.058662,3.51972
82,7,شایان,2,23,24,60,A,1000000000,5.237331e+07,1.666667e+09,3.47652,0.057942,3.47652
83,94,شایان,6,23,36,70,D,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662,3.47634
84,99,شایان,6,23,36,70,E,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662,3.47634
85,38,شایان,2,23,24,55,B,1000000000,5.237331e+07,1.818182e+09,3.33531,0.060642,3.33531
86,43,شایان,3,18,12,100,B,1000000000,9.167999e+07,1.000000e+09,3.22740,0.032274,3.22740
87,6,شایان,2,23,24,55,A,1000000000,5.237331e+07,1.818182e+09,3.18681,0.057942,3.18681
88,53,شایان,6,14,12,110,B,1000000000,8.978712e+07,9.090909e+08,3.14820,0.028620,3.14820
89,131,نیک‌وام,4,4,36,40,B,1000000000,2.952399e+07,2.500000e+09,3.10080,0.077520,3.10080
90,35,شایان,1,23,12,50,B,1000000000,9.407632e+07,2.000000e+09,3.08610,0.061722,3.08610
91,48,شایان,3,23,36,50,B,1000000000,3.870972e+07,2.000000e+09,3.06810,0.061362,3.06810
92,11,شایان,3,18,12,100,A,1000000000,9.167999e+07,1.000000e+09,2.95740,0.029574,2.95740
93,3,شایان,1,23,12,50,A,1000000000,9.407632e+07,2.000000e+09,2.95110,0.059022,2.95110
94,136,نیک‌وام,6,4,48,45,B,1000000000,2.257905e+07,2.222222e+09,2.93760,0.065280,2.93760
95,16,شایان,3,23,36,50,A,1000000000,3.870972e+07,2.000000e+09,2.93310,0.058662,2.93310
96,112,نیک‌وام,4,4,36,40,A,1000000000,2.952399e+07,2.500000e+09,2.89680,0.072420,2.89680
97,78,شایان,3,23,36,50,C,1000000000,3.870972e+07,2.000000e+09,2.86560,0.057312,2.86560
98,21,شایان,6,14,12,110,A,1000000000,8.978712e+07,9.090909e+08,2.85120,0.025920,2.85120
99,70,شایان,2,23,24,50,C,1000000000,5.237331e+07,2.000000e+09,2.82960,0.056592,2.82960

In [104]:
df_reduced.sort_values(by="coef_sort", inplace=True, ascending=False)

In [105]:
df_reduced

,id,nickname,deposit_duration,interest_rate,repayment_duration,loan_coefficient,credit_score,loan_amount,monthly_repayment,deposit_amount,sortOrder,pre_sortOrder,coef_sort
0,2,بهان(بدون ضامن),3,23,60,1000,B,1000000000,2.819047e+07,1.000000e+08,101.67000,0.101670,101.67000
1,1,بهان(بدون ضامن),3,23,60,1000,A,1000000000,2.819047e+07,1.000000e+08,97.17000,0.097170,97.17000
2,101,فرابانک,3,23,36,1000,B,1000000000,3.870972e+07,1.000000e+08,61.36200,0.061362,61.36200
3,100,فرابانک,3,23,36,1000,A,1000000000,3.870972e+07,1.000000e+08,58.66200,0.058662,58.66200
4,102,فرابانک,3,23,36,1000,C,1000000000,3.870972e+07,1.000000e+08,57.31200,0.057312,57.31200
5,45,شایان,3,23,12,450,B,1000000000,9.407632e+07,2.222222e+08,26.96490,0.059922,26.96490
6,13,شایان,3,23,12,450,A,1000000000,9.407632e+07,2.222222e+08,25.74990,0.057222,25.74990
7,137,نیک‌وام,12,4,12,320,B,1000000000,8.514990e+07,3.125000e+08,22.84800,0.071400,22.84800
8,118,نیک‌وام,12,4,12,320,A,1000000000,8.514990e+07,3.125000e+08,21.21600,0.066300,21.21600
9,156,نیک‌وام,12,4,12,320,C,1000000000,8.514990e+07,3.125000e+08,20.40000,0.063750,20.40000
10,37,شایان,2,23,12,300,B,1000000000,9.407632e+07,3.333333e+08,17.97660,0.059922,17.97660
11,5,شایان,2,23,12,300,A,1000000000,9.407632e+07,3.333333e+08,17.16660,0.057222,17.16660
12,74,شایان,3,23,12,300,C,1000000000,9.407632e+07,3.333333e+08,16.76160,0.055872,16.76160
13,44,شایان,3,23,12,200,B,1000000000,9.407632e+07,5.000000e+08,11.98440,0.059922,11.98440
14,138,نیک‌وام,12,4,24,160,B,1000000000,4.342492e+07,6.250000e+08,11.64160,0.072760,11.64160
15,12,شایان,3,23,12,200,A,1000000000,9.407632e+07,5.000000e+08,11.44440,0.057222,11.44440
16,133,نیک‌وام,6,4,12,160,B,1000000000,8.514990e+07,6.250000e+08,11.42400,0.071400,11.42400
17,60,شایان,6,23,24,200,B,1000000000,5.237331e+07,5.000000e+08,11.40840,0.057042,11.40840
18,68,شایان,2,23,12,200,C,1000000000,9.407632e+07,5.000000e+08,11.17440,0.055872,11.17440
19,28,شایان,6,23,24,200,A,1000000000,5.237331e+07,5.000000e+08,10.86840,0.054342,10.86840
20,119,نیک‌وام,12,4,24,160,A,1000000000,4.342492e+07,6.250000e+08,10.82560,0.067660,10.82560
21,114,نیک‌وام,6,4,12,160,A,1000000000,8.514990e+07,6.250000e+08,10.60800,0.066300,10.60800
22,157,نیک‌وام,12,4,24,160,C,1000000000,4.342492e+07,6.250000e+08,10.41760,0.065110,10.41760
23,152,نیک‌وام,6,4,12,160,C,1000000000,8.514990e+07,6.250000e+08,10.20000,0.063750,10.20000
24,73,شایان,3,23,12,175,C,1000000000,9.407632e+07,5.714286e+08,9.77760,0.055872,9.77760
25,36,شایان,2,23,12,150,B,1000000000,9.407632e+07,6.666667e+08,8.98830,0.059922,8.98830
26,4,شایان,2,23,12,150,A,1000000000,9.407632e+07,6.666667e+08,8.58330,0.057222,8.58330
27,59,شایان,6,23,24,150,B,1000000000,5.237331e+07,6.666667e+08,8.55630,0.057042,8.55630
28,129,نیک‌وام,4,4,12,110,B,1000000000,8.514990e+07,9.090909e+08,8.22800,0.074800,8.22800
29,139,نیک‌وام,12,4,36,110,B,1000000000,2.952399e+07,9.090909e+08,8.15320,0.074120,8.15320
30,27,شایان,6,23,24,150,A,1000000000,5.237331e+07,6.666667e+08,8.15130,0.054342,8.15130
31,86,شایان,6,23,24,150,C,1000000000,5.237331e+07,6.666667e+08,7.94880,0.052992,7.94880
32,110,نیک‌وام,4,4,12,110,A,1000000000,8.514990e+07,9.090909e+08,7.66700,0.069700,7.66700
33,120,نیک‌وام,12,4,36,110,A,1000000000,2.952399e+07,9.090909e+08,7.59220,0.069020,7.59220
34,148,نیک‌وام,4,4,12,110,C,1000000000,8.514990e+07,9.090909e+08,7.38650,0.067150,7.38650
35,158,نیک‌وام,12,4,36,110,C,1000000000,2.952399e+07,9.090909e+08,7.31170,0.066470,7.31170
36,64,شایان,6,23,36,125,B,1000000000,3.870972e+07,8.000000e+08,7.22025,0.057762,7.22025
37,32,شایان,6,23,36,125,A,1000000000,3.870972e+07,8.000000e+08,6.88275,0.055062,6.88275
38,67,شایان,2,23,12,120,C,1000000000,9.407632e+07,8.333333e+08,6.70464,0.055872,6.70464
39,85,شایان,6,23,24,125,C,1000000000,5.237331e+07,8.000000e+08,6.62400,0.052992,6.62400
40,63,شایان,6,23,36,110,B,1000000000,3.870972e+07,9.090909e+08,6.35382,0.057762,6.35382
41,47,شایان,3,23,24,100,B,1000000000,5.237331e+07,1.000000e+09,6.06420,0.060642,6.06420
42,31,شایان,6,23,36,110,A,1000000000,3.870972e+07,9.090909e+08,6.05682,0.055062,6.05682
43,134,نیک‌وام,6,4,24,80,B,1000000000,4.342492e+07,1.250000e+09,5.82080,0.072760,5.82080
44,15,شایان,3,23,24,100,A,1000000000,5.237331e+07,1.000000e+09,5.79420,0.057942,5.79420
45,55,شایان,6,18,12,200,B,1000000000,9.167999e+07,5.000000e+08,5.73480,0.028674,5.73480
46,90,شایان,3,23,12,110,D,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822,5.70042
47,95,شایان,3,23,12,110,E,1000000000,9.407632e+07,9.090909e+08,5.70042,0.051822,5.70042
48,115,نیک‌وام,6,4,24,80,A,1000000000,4.342492e+07,1.250000e+09,5.41280,0.067660,5.41280
49,89,شایان,6,23,36,100,C,1000000000,3.870972e+07,1.000000e+09,5.37120,0.053712,5.37120
50,140,نیک‌وام,12,4,48,80,B,1000000000,2.257905e+07,1.250000e+09,5.22240,0.065280,5.22240
51,153,نیک‌وام,6,4,24,80,C,1000000000,4.342492e+07,1.250000e+09,5.20880,0.065110,5.20880
52,23,شایان,6,18,12,200,A,1000000000,9.167999e+07,5.000000e+08,5.19480,0.025974,5.19480
53,93,شایان,6,23,24,100,D,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942,4.89420
54,98,شایان,6,23,24,100,E,1000000000,5.237331e+07,1.000000e+09,4.89420,0.048942,4.89420
55,54,شایان,6,18,12,170,B,1000000000,9.167999e+07,5.882353e+08,4.87458,0.028674,4.87458
56,46,شایان,3,23,24,80,B,1000000000,5.237331e+07,1.250000e+09,4.85136,0.060642,4.85136
57,88,شایان,6,23,36,90,C,1000000000,3.870972e+07,1.111111e+09,4.83408,0.053712,4.83408
58,121,نیک‌وام,12,4,48,80,A,1000000000,2.257905e+07,1.250000e+09,4.81440,0.060180,4.81440
59,66,شایان,6,23,48,90,B,1000000000,3.205147e+07,1.111111e+09,4.77738,0.053082,4.77738
60,14,شایان,3,23,24,80,A,1000000000,5.237331e+07,1.250000e+09,4.63536,0.057942,4.63536
61,159,نیک‌وام,12,4,48,80,C,1000000000,2.257905e+07,1.250000e+09,4.61040,0.057630,4.61040
62,34,شایان,6,23,48,90,A,1000000000,3.205147e+07,1.111111e+09,4.53438,0.050382,4.53438
63,76,شایان,3,23,24,80,C,1000000000,5.237331e+07,1.250000e+09,4.52736,0.056592,4.52736
64,135,نیک‌وام,6,4,36,60,B,1000000000,2.952399e+07,1.666667e+09,4.44720,0.074120,4.44720
65,82,شایان,6,18,12,180,C,1000000000,9.167999e+07,5.555556e+08,4.43232,0.024624,4.43232
66,22,شایان,6,18,12,170,A,1000000000,9.167999e+07,5.882353e+08,4.41558,0.025974,4.41558
67,125,نیک‌وام,2,4,12,55,B,1000000000,8.514990e+07,1.818182e+09,4.30100,0.078200,4.30100
68,130,نیک‌وام,4,4,24,55,B,1000000000,4.342492e+07,1.818182e+09,4.18880,0.076160,4.18880
69,116,نیک‌وام,6,4,36,60,A,1000000000,2.952399e+07,1.666667e+09,4.14120,0.069020,4.14120
70,106,نیک‌وام,2,4,12,55,A,1000000000,8.514990e+07,1.818182e+09,4.02050,0.073100,4.02050
71,154,نیک‌وام,6,4,36,60,C,1000000000,2.952399e+07,1.666667e+09,3.98820,0.066470,3.98820
72,65,شایان,6,23,48,75,B,1000000000,3.205147e+07,1.333333e+09,3.98115,0.053082,3.98115
73,75,شایان,3,23,24,70,C,1000000000,5.237331e+07,1.428571e+09,3.96144,0.056592,3.96144
74,111,نیک‌وام,4,4,24,55,A,1000000000,4.342492e+07,1.818182e+09,3.90830,0.071060,3.90830
75,144,نیک‌وام,2,4,12,55,C,1000000000,8.514990e+07,1.818182e+09,3.88025,0.070550,3.88025
76,33,شایان,6,23,48,75,A,1000000000,3.205147e+07,1.333333e+09,3.77865,0.050382,3.77865
77,149,نیک‌وام,4,4,24,55,C,1000000000,4.342492e+07,1.818182e+09,3.76805,0.068510,3.76805
78,81,شایان,6,18,12,150,C,1000000000,9.167999e+07,6.666667e+08,3.69360,0.024624,3.69360
79,49,شایان,3,23,36,60,B,1000000000,3.870972e+07,1.666667e+09,3.68172,0.061362,3.68172
80,39,شایان,2,23,24,60,B,1000000000,5.237331e+07,1.666667e+09,3.63852,0.060642,3.63852
81,17,شایان,3,23,36,60,A,1000000000,3.870972e+07,1.666667e+09,3.51972,0.058662,3.51972
82,7,شایان,2,23,24,60,A,1000000000,5.237331e+07,1.666667e+09,3.47652,0.057942,3.47652
83,94,شایان,6,23,36,70,D,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662,3.47634
84,99,شایان,6,23,36,70,E,1000000000,3.870972e+07,1.428571e+09,3.47634,0.049662,3.47634
85,38,شایان,2,23,24,55,B,1000000000,5.237331e+07,1.818182e+09,3.33531,0.060642,3.33531
86,43,شایان,3,18,12,100,B,1000000000,9.167999e+07,1.000000e+09,3.22740,0.032274,3.22740
87,6,شایان,2,23,24,55,A,1000000000,5.237331e+07,1.818182e+09,3.18681,0.057942,3.18681
88,53,شایان,6,14,12,110,B,1000000000,8.978712e+07,9.090909e+08,3.14820,0.028620,3.14820
89,131,نیک‌وام,4,4,36,40,B,1000000000,2.952399e+07,2.500000e+09,3.10080,0.077520,3.10080
90,35,شایان,1,23,12,50,B,1000000000,9.407632e+07,2.000000e+09,3.08610,0.061722,3.08610
91,48,شایان,3,23,36,50,B,1000000000,3.870972e+07,2.000000e+09,3.06810,0.061362,3.06810
92,11,شایان,3,18,12,100,A,1000000000,9.167999e+07,1.000000e+09,2.95740,0.029574,2.95740
93,3,شایان,1,23,12,50,A,1000000000,9.407632e+07,2.000000e+09,2.95110,0.059022,2.95110
94,136,نیک‌وام,6,4,48,45,B,1000000000,2.257905e+07,2.222222e+09,2.93760,0.065280,2.93760
95,16,شایان,3,23,36,50,A,1000000000,3.870972e+07,2.000000e+09,2.93310,0.058662,2.93310
96,112,نیک‌وام,4,4,36,40,A,1000000000,2.952399e+07,2.500000e+09,2.89680,0.072420,2.89680
97,78,شایان,3,23,36,50,C,1000000000,3.870972e+07,2.000000e+09,2.86560,0.057312,2.86560
98,21,شایان,6,14,12,110,A,1000000000,8.978712e+07,9.090909e+08,2.85120,0.025920,2.85120
99,70,شایان,2,23,24,50,C,1000000000,5.237331e+07,2.000000e+09,2.82960,0.056592,2.82960
100,150,نیک‌وام,4,4,36,40,C,1000000000,2.952399e+07,2.500000e+09,2.79480,0.069870,2.79480
101,117,نیک‌وام,6,4,48,45,A,1000000000,2.257905e+07,2.222222e+09,2.70810,0.060180,2.70810
102,155,نیک‌وام,6,4,48,45,C,1000000000,2.257905e+07,2.222222e+09,2.59335,0.057630,2.59335
103,42,شایان,3,18,12,80,B,1000000000,9.167999e+07,1.250000e+09,2.58192,0.032274,2.58192
104,52,شایان,6,14,12,90,B,1000000000,8.978712e+07,1.111111e+09,2.57580,0.028620,2.57580
105,69,شایان,2,23,24,45,C,1000000000,5.237331e+07,2.222222e+09,2.54664,0.056592,2.54664
106,72,شایان,3,18,12,90,C,1000000000,9.167999e+07,1.111111e+09,2.54016,0.028224,2.54016
107,126,نیک‌وام,2,4,24,30,B,1000000000,4.342492e+07,3.333333e+09,2.38680,0.079560,2.38680
108,10,شایان,3,18,12,80,A,1000000000,9.167999e+07,1.250000e+09,2.36592,0.029574,2.36592
109,91,شایان,3,23,24,45,D,1000000000,5.237331e+07,2.222222e+09,2.36439,0.052542,2.36439
110,96,شایان,3,23,24,45,E,1000000000,5.237331e+07,2.222222e+09,2.36439,0.052542,2.36439
111,20,شایان,6,14,12,90,A,1000000000,8.978712e+07,1.111111e+09,2.33280,0.025920,2.33280
112,77,شایان,3,23,36,40,C,1000000000,3.870972e+07,2.500000e+09,2.29248,0.057312,2.29248
113,107,نیک‌وام,2,4,24,30,A,1000000000,4.342492e+07,3.333333e+09,2.23380,0.074460,2.23380
114,80,شایان,6,14,12,90,C,1000000000,8.978712e+07,1.111111e+09,2.21130,0.024570,2.21130
115,57,شایان,6,18,24,75,B,1000000000,4.992410e+07,1.333333e+09,2.20455,0.029394,2.20455
116,122,نیک‌وام,1,4,12,27,B,1000000000,8.514990e+07,3.703704e+09,2.20320,0.081600,2.20320
117,145,نیک‌وام,2,4,24,30,C,1000000000,4.342492e+07,3.333333e+09,2.15730,0.071910,2.15730
118,41,شایان,2,23,36,35,B,1000000000,3.870972e+07,2.857143e+09,2.14767,0.061362,2.14767
119,103,نیک‌وام,1,4,12,27,A,1000000000,8.514990e+07,3.703704e+09,2.06550,0.076500,2.06550
120,132,نیک‌وام,4,4,48,30,B,1000000000,2.257905e+07,3.333333e+09,2.06040,0.068680,2.06040
121,58,شایان,6,18,24,70,B,1000000000,4.992410e+07,1.428571e+09,2.05758,0.029394,2.05758
122,9,شایان,2,23,36,35,A,1000000000,3.870972e+07,2.857143e+09,2.05317,0.058662,2.05317
123,25,شایان,6,18,24,75,A,1000000000,4.992410e+07,1.333333e+09,2.00205,0.026694,2.00205
124,141,نیک‌وام,1,4,12,27,C,1000000000,8.514990e+07,3.703704e+09,1.99665,0.073950,1.99665
125,51,شایان,3,23,48,35,B,1000000000,3.205147e+07,2.857143e+09,1.98387,0.056682,1.98387
126,71,شایان,3,18,12,70,C,1000000000,9.167999e+07,1.428571e+09,1.97568,0.028224,1.97568
127,113,نیک‌وام,4,4,48,30,A,1000000000,2.257905e+07,3.333333e+09,1.90740,0.063580,1.90740
128,19,شایان,3,23,48,35,A,1000000000,3.205147e+07,2.857143e+09,1.88937,0.053982,1.88937
129,26,شایان,6,18,24,70,A,1000000000,4.992410e+07,1.428571e+09,1.86858,0.026694,1.86858
130,79,شایان,6,14,12,75,C,1000000000,8.978712e+07,1.333333e+09,1.84275,0.024570,1.84275
131,40,شایان,2,23,36,30,B,1000000000,3.870972e+07,3.333333e+09,1.84086,0.061362,1.84086
132,151,نیک‌وام,4,4,48,30,C,1000000000,2.257905e+07,3.333333e+09,1.83090,0.061030,1.83090
133,8,شایان,2,23,36,30,A,1000000000,3.870972e+07,3.333333e+09,1.75986,0.058662,1.75986
134,50,شایان,3,23,48,30,B,1000000000,3.205147e+07,3.333333e+09,1.70046,0.056682,1.70046
135,18,شایان,3,23,48,30,A,1000000000,3.205147e+07,3.333333e+09,1.61946,0.053982,1.61946
136,127,نیک‌وام,2,4,36,20,B,1000000000,2.952399e+07,5.000000e+09,1.61840,0.080920,1.61840
137,92,شایان,3,23,36,30,D,1000000000,3.870972e+07,3.333333e+09,1.59786,0.053262,1.59786
138,97,شایان,3,23,36,30,E,1000000000,3.870972e+07,3.333333e+09,1.59786,0.053262,1.59786
139,83,شایان,6,18,24,60,C,1000000000,4.992410e+07,1.666667e+09,1.52064,0.025344,1.52064
140,108,نیک‌وام,2,4,36,20,A,1000000000,2.952399e+07,5.000000e+09,1.51640,0.075820,1.51640
141,61,شایان,6,18,36,50,B,1000000000,3.615240e+07,2.000000e+09,1.50570,0.030114,1.50570
142,146,نیک‌وام,2,4,36,20,C,1000000000,2.952399e+07,5.000000e+09,1.46540,0.073270,1.46540
143,84,شایان,6,18,24,55,C,1000000000,4.992410e+07,1.818182e+09,1.39392,0.025344,1.39392
144,29,شایان,6,18,36,50,A,1000000000,3.615240e+07,2.000000e+09,1.37070,0.027414,1.37070
145,62,شایان,6,18,36,45,B,1000000000,3.615240e+07,2.222222e+09,1.35513,0.030114,1.35513
146,56,شایان,6,14,24,45,B,1000000000,4.801288e+07,2.222222e+09,1.32030,0.029340,1.32030
147,123,نیک‌وام,1,4,24,15,B,1000000000,4.342492e+07,6.666667e+09,1.24440,0.082960,1.24440
148,30,شایان,6,18,36,45,A,1000000000,3.615240e+07,2.222222e+09,1.23363,0.027414,1.23363
149,24,شایان,6,14,24,45,A,1000000000,4.801288e+07,2.222222e+09,1.19880,0.026640,1.19880
150,104,نیک‌وام,1,4,24,15,A,1000000000,4.342492e+07,6.666667e+09,1.16790,0.077860,1.16790
151,142,نیک‌وام,1,4,24,15,C,1000000000,4.342492e+07,6.666667e+09,1.12965,0.075310,1.12965
152,128,نیک‌وام,2,4,48,15,B,1000000000,2.257905e+07,6.666667e+09,1.08120,0.072080,1.08120
153,87,شایان,6,18,36,40,C,1000000000,3.615240e+07,2.500000e+09,1.04256,0.026064,1.04256
154,109,نیک‌وام,2,4,48,15,A,1000000000,2.257905e+07,6.666667e+09,1.00470,0.066980,1.00470
155,147,نیک‌وام,2,4,48,15,C,1000000000,2.257905e+07,6.666667e+09,0.96645,0.064430,0.96645
156,124,نیک‌وام,1,4,36,10,B,1000000000,2.952399e+07,1.000000e+10,0.84320,0.084320,0.84320
157,105,نیک‌وام,1,4,36,10,A,1000000000,2.952399e+07,1.000000e+10,0.79220,0.079220,0.79220
158,143,نیک‌وام,1,4,36,10,C,1000000000,2.952399e+07,1.000000e+10,0.76670,0.076670,0.76670

In [108]:
# determining the name of the file
file_name = 'TestSorting.xlsx'

# saving the excel
df_reduced.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.

In [106]:
# df_reduced.sort_values(by="loan_coefficient", inplace=True, ascending=False)

In [107]:
# df_reduced